- .editorconfig
- src/button/button.tsx
- src/carousel/carousel.tsx
- src/colors/colors.stories.tsx
- src/colors/colors.tsx
- src/footer/footer.tsx
- src/header/header.tsx
- src/paragraph/paragraph.tsx
- src/schedule/schedule-item.tsx
- src/speaker-details/speaker-details.tsx
- src/split-section/split-section.tsx
- src/style.css
- src/ticket/lanyard.tsx
- src/ticket/ticket.tsx
- src/types.ts
- tailwind.config.js
New colors for the design system
> Add new colors

- src/button/button.stories.tsx
- src/button/button.tsx
- src/text/text.tsx
- tailwind.config.js
> New Button component

- src/button/button.tsx
- src/container/container.tsx
- src/illustrations/snake-body.tsx
- src/index.ts
- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/index.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
- src/page/page.stories.tsx
- src/section/section.tsx
- src/slider-grid-section/index.tsx
- src/slider-grid-section/slider-grid-section.stories.tsx
- src/slider-grid-section/slider-grid-section.tsx
- src/spacer/spacer.tsx
- src/split-section/split-section.tsx
- src/style.css
- src/text/text.tsx
- tailwind.config.js
> New layouts components

- src/split-section/split-section.tsx
> Fix slight misalign with two sections

- src/grid-section/grid-section.stories.tsx
- src/grid-section/grid-section.tsx
- src/grid-section/index.tsx
- src/index.ts
- src/slider-grid-section/slider-grid-section.stories.tsx
- src/spacer/spacer.tsx
> Grid Section component

- src/index.ts
- src/tag/index.tsx
- src/tag/tag.stories.tsx
- src/tag/tag.tsx
> Tag component

- src/index.ts
- src/multiple-parts-card/card-part-two-sides.tsx
- src/multiple-parts-card/index.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
> Card Part: Two sides

- src/button/basic-button.tsx
- src/button/button.stories.tsx
> Basic Button: Support for disabled state

- src/multiple-parts-card/multiple-parts-card.stories.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
> MultiPartCard: Add ability to open expandable content on focus

- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
> Fix focus handling on expandable card part

- src/grid-section/grid-section.stories.tsx
- src/grid-section/grid-section.tsx
- src/grid/grid.tsx
- src/slider-grid-section/slider-grid-section.stories.tsx
- src/slider-grid-section/slider-grid-section.tsx
> Grid: Sizing and snake background

- package.json
- pnpm-lock.yaml
- src/schedule/ical-link.tsx
> Remove ical dep

- src/button/basic-button.tsx
- src/button/button.stories.tsx
- src/button/button.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
> Button: Update API props and support links

- src/footer/footer.tsx
- src/link/link.tsx
- src/navbar/menu.tsx
> Link: Hover color as prop

- src/grid-section/grid-section.stories.tsx
- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
- src/page/page.stories.tsx
- src/slider-grid-section/slider-grid-section.stories.tsx
> MultiPartsCard: More consistent API by removing title

- src/icons/arrow.tsx
- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
> MultiPartsCard: Support for right side icons

- src/section/section.stories.tsx
- src/section/section.tsx
> Section: add support for background color

- src/input/input.tsx
- src/select/select.tsx
- src/textarea/textarea.tsx
> Form inputs: Fix weights

- src/index.ts
- src/multiple-parts-card-collection/index.tsx
- src/multiple-parts-card-collection/multiple-parts-card-collection.tsx
- src/multiple-parts-card-collection/mutiple-parts-card-collection.stories.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
- src/style.css
> Add MultiplePartsCardCollection component

- src/container/container.stories.tsx
- src/container/container.tsx
- src/grid/grid-column.tsx
- src/grid/grid.tsx
- src/link/link.tsx
- src/multiple-parts-card/multiple-parts-card.tsx
- src/section/section.stories.tsx
- src/section/section.tsx
- src/slider-grid/slider-grid.stories.tsx
- src/slider-grid/slider-grid.tsx
- src/spacer/spacer.tsx
- src/style.css
- tailwind.config.js
> Layout fixes and snake support in sections

- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
- src/speaker-card/speaker-card.tsx
> Multicolor background for CardPart

- src/layout-content/layout-content.tsx
> Layout content more options

- src/index.ts
- src/input-number/index.tsx
- src/input-number/input-number.stories.tsx
- src/input-number/input-number.tsx
- src/style.css
> Add InputNumber component

- src/colors-utils.tsx
- src/input-number/input-number.tsx
- src/multiple-parts-card/card-part.tsx
- src/multiple-parts-card/multiple-parts-card.stories.tsx
- Show text when on hover
- Use css
- Add hover color
> CardPart: Add hoverColor

- src/index.ts
- src/sponsors-grid/index.tsx
- src/sponsors-grid/sponsors-grid.stories.tsx
- src/sponsors-grid/sponsors-grid.tsx
> Sponsors Grid

- src/container/container.tsx
- src/link/link.tsx
- src/multiple-parts-card/card-part-increments.tsx
- src/multiple-parts-card/card-part-options.tsx
- src/slider-grid/slider-grid.stories.tsx
- src/slider-grid/slider-grid.tsx
- src/split-section/split-section.tsx
- src/text/text.tsx
> SliderGrid improved usage with different cols, spacing, typings

- src/slider-grid/slider-grid.stories.tsx
- src/slider-grid/slider-grid.tsx
> SliderGrid: More flexible when items and cols do not match

- .storybook/preview.js
- package.json
- pnpm-lock.yaml
- rollup.config.js
- src/avatar-group/avatar-group.stories.tsx
- src/avatar-group/avatar-group.tsx
- src/avatar-group/index.tsx
- src/avatar/avatar.stories.tsx
- src/avatar/avatar.tsx
- src/avatar/index.tsx
- src/base.css
- src/custom.css
- src/days-selector/days-selector.stories.tsx
- src/days-selector/days-selector.tsx
- src/days-selector/index.tsx
- src/horizontal-stack/horizontal-stack.tsx
- src/icons/heart.tsx
- src/icons/icons.stories.tsx
- src/icons/index.ts
- src/icons/live.tsx
- src/index.ts
- src/navbar/header-bar.tsx
- src/navbar/navbar.tsx
- src/schedule/schedule-item-card.tsx
- src/separator/separator.tsx
- src/vertical-stack/vertical-stack.tsx
- tailwind.config.js
> Schedule UI components

- src/days-selector/days-selector.stories.tsx
- src/days-selector/days-selector.tsx
> Center days selector

- src/slider-grid/slider-grid.tsx
> Fix slider grid when remounting children

- src/navbar/menu.tsx
Closes #pythonitalia/pycon/issues/3370
> Use caramel for hover style in the navbar

- src/dynamic-html-text/dynamic-html-text.tsx
> DynamicHTMLText: Fix `li` margin

- src/filter-bar/filter-bar.tsx
> Filterbar fixes

- src/filter-bar/filter-bar.tsx
> Close FilterBar on reset

- src/speaker-card/speaker-card.stories.tsx
- src/speaker-card/speaker-card.tsx
> Add support for more talk info

- src/separator/separator.stories.tsx
- src/separator/separator.tsx
- src/styled-text/styled-text.stories.tsx
> Separator Escape Container mobile only

- src/avatar/avatar.tsx
- src/button/button.tsx
- src/colors-utils.tsx
- src/countdown/countdown.tsx
- src/layout-content/layout-content.tsx
- src/multiple-parts-card/card-part.tsx
- src/navbar/action-item.tsx
- src/navbar/navbar.stories.tsx
- src/navbar/types.tsx
- src/schedule/schedule-item-card.tsx
- src/section/section.tsx
- tailwind.config.js
> Refactor colors and Navbar options

- .github/workflows/deploy.yml
- src/file-input/file-input.stories.tsx
- src/file-input/file-input.tsx
- src/file-input/index.tsx
- src/icons/file-upload.tsx
- src/icons/icons.ts
- src/icons/index.ts
- src/icons/types.ts
- src/index.ts
> File input UI

- src/hero-illustration/index.tsx
- src/index.ts
> Add missing exports for hero illustration for Bologna

- src/hero-illustration/hero-illustration-bologna.tsx
> Recenter illustration

- src/footer/footer.tsx
- src/lang/it.tsx
> Remove powered by Vercel
